import { chromium } from "@playwright/test";
const browser = await chromium.launch({ args: ["--use-angle=d3d11", "--use-gl=angle"] });
const context = await browser.newContext({ viewport: { width: 1280, height: 800 }, userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" });
const page = await context.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message.slice(0, 120)));
await page.goto("http://localhost:3000/fr/projets", { waitUntil: "networkidle" });
await page.waitForFunction(() => document.documentElement.dataset.loaded === "true", null, { timeout: 60000 });
await page.waitForTimeout(1500);
const state = () => page.evaluate(() => ({ sceneOnly: document.body.classList.contains("nahual-scene-only"), cinematic: document.body.classList.contains("nahual-cinematic"), scrollY: Math.round(window.scrollY), stored: sessionStorage.getItem("nahual-scene-only"), toast: [...document.querySelectorAll('[role="status"]')].map((e) => e.textContent).find((t) => t && t.includes("Tenochtitlan")) ?? null, tPressed: document.querySelector('button[aria-pressed]:nth-of-type(3)')?.getAttribute("aria-pressed") }));
console.log("avant   ", JSON.stringify(await state()));
await page.keyboard.press("t");
await page.waitForTimeout(500);
console.log("T +0.5s ", JSON.stringify(await state()));
await page.waitForTimeout(5000);
console.log("T +5.5s ", JSON.stringify(await state()));
await page.mouse.wheel(0, 10);
await page.waitForTimeout(500);
console.log("apres geste", JSON.stringify(await state()));
// Texte deja masque avant : doit rester masque apres.
await page.keyboard.press("h"); await page.waitForTimeout(300);
await page.keyboard.press("t"); await page.waitForTimeout(800);
console.log("H puis T ", JSON.stringify(await state()));
await page.mouse.wheel(0, 10); await page.waitForTimeout(500);
console.log("apres geste 2", JSON.stringify(await state()));
console.log("erreurs:", errors);
await browser.close();
