import { chromium } from "@playwright/test";
const OUT = "C:/Users/sylva/AppData/Local/Temp/claude/C--Windows-System32/86ddb9fc-c7f5-4872-9d73-b603ad93d9cf/scratchpad";
const browser = await chromium.launch({ args: ["--enable-unsafe-webgpu", "--ignore-gpu-blocklist", "--use-angle=d3d11", "--use-gl=angle"] });
const context = await browser.newContext({ viewport: { width: 1280, height: 800 }, userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" });
const page = await context.newPage();
await page.goto(`http://localhost:3000/fr?t=0.5&gpu=1&scene=1`, { waitUntil: "networkidle" });
await page.waitForFunction(() => document.documentElement.dataset.loaded === "true", null, { timeout: 60000 });
await page.waitForTimeout(4500);
const find = `let g = null; window.__nahualScene.traverse((o) => { if (o.isInstancedMesh && o.count > 10000) g = o; });`;
const info = await page.evaluate(`(() => { ${find} const m = g.material; return { fog: m.fog, lights: m.lights, side: m.side, roughness: m.roughness, metalness: m.metalness, color: m.color.getHexString(), emissiveIntensity: m.emissiveIntensity, vertexColors: m.vertexColors, hasInstanceColor: !!g.instanceColor, colorNode: !!m.colorNode, positionNode: !!m.positionNode, envMapIntensity: m.envMapIntensity, transparent: m.transparent, opacity: m.opacity, uTintMix: m.uniforms?.uTintMix?.value, uGreenBase: m.uniforms?.uGreenBase?.value, uTint: m.uniforms?.uTint?.value?.getHexString?.() }; })()`);
console.log(JSON.stringify(info));
await page.evaluate(`(() => { ${find} g.material.__color = g.material.colorNode; g.material.colorNode = null; g.material.needsUpdate = true; })()`);
await page.waitForTimeout(1500);
await page.screenshot({ path: `${OUT}/gc_nocolornode.png` });
await page.evaluate(`(() => { ${find} g.material.colorNode = g.material.__color; g.material.fog = false; g.material.needsUpdate = true; })()`);
await page.waitForTimeout(1500);
await page.screenshot({ path: `${OUT}/gc_nofog.png` });
await browser.close();
