import { chromium } from "@playwright/test";
const OUT = "C:/Users/sylva/AppData/Local/Temp/claude/C--Windows-System32/86ddb9fc-c7f5-4872-9d73-b603ad93d9cf/scratchpad";
const browser = await chromium.launch({ args: ["--enable-unsafe-webgpu", "--ignore-gpu-blocklist", "--use-angle=d3d11", "--use-gl=angle"] });
const context = await browser.newContext({ viewport: { width: 1280, height: 800 }, userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" });
const page = await context.newPage();
await page.goto("http://localhost:3000/fr/projets?gpu=1&xiuhcoatl=1&t=0.02&scene=1", { waitUntil: "networkidle" });
await page.waitForFunction(() => !!window.__nahualScene, null, { timeout: 30000 });
await page.waitForFunction(() => document.documentElement.dataset.loaded === "true", null, { timeout: 60000 });
await page.waitForTimeout(4500);
const find = `let s = null; window.__nahualScene.traverse((o) => { if (o.isSprite && o.material?.uniforms?.uScale && o.geometry?.getAttribute("aAlpha")) s = o; });`;
await page.evaluate(`${find} s.material.uniforms.uScale.value = 2400; window.__bigStars = true;`);
await page.waitForTimeout(600);
await page.screenshot({ path: `${OUT}/iso_big.png` });
await page.evaluate(`${find} s.material.uniforms.uScale.value = 240; s.material.opacityNode = null; s.material.needsUpdate = true;`);
await page.waitForTimeout(800);
await page.screenshot({ path: `${OUT}/iso_noopacity.png` });
await page.evaluate(`${find} s.material.colorNode = null; s.material.needsUpdate = true;`);
await page.waitForTimeout(800);
await page.screenshot({ path: `${OUT}/iso_nocolor.png` });
await browser.close();
