import { chromium } from "@playwright/test";
const OUT = "C:/Users/sylva/AppData/Local/Temp/claude/C--Windows-System32/86ddb9fc-c7f5-4872-9d73-b603ad93d9cf/scratchpad";
const gpu = process.argv[2] ?? "1";
const browser = await chromium.launch({ args: ["--enable-unsafe-webgpu", "--ignore-gpu-blocklist", "--use-angle=d3d11", "--use-gl=angle"] });
const context = await browser.newContext({ viewport: { width: 1280, height: 800 }, userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" });
const page = await context.newPage();
const errors = [];
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text().slice(0, 300)); });
await page.goto(`http://localhost:3000/fr/projets?gpu=${gpu}&xiuhcoatl=1&t=0.02&scene=1`, { waitUntil: "networkidle" });
await page.waitForFunction(() => !!window.__nahualScene, null, { timeout: 30000 });
await page.waitForFunction(() => document.documentElement.dataset.loaded === "true", null, { timeout: 60000 });
await page.waitForTimeout(4500);
await page.screenshot({ path: `${OUT}/stars_exp${gpu}.png` });
const stats = await page.evaluate(() => {
  let s = null; window.__nahualScene.traverse((o) => { if ((o.isSprite || o.isPoints) && o.material?.uniforms?.uScale && o.geometry?.getAttribute("aAlpha")) s = o; });
  if (!s) return "no stars";
  const g = s.geometry; const st = (n) => { const a = g.getAttribute(n).array; let mn = 1e9, mx = -1e9, sum = 0, nz = 0; for (const v of a) { mn = Math.min(mn, v); mx = Math.max(mx, v); sum += v; if (v > 0) nz++; } return { mn, mx, mean: sum / a.length, nz, len: a.length }; };
  const pos = g.getAttribute(g.getAttribute("aPosition") ? "aPosition" : "position").array; let far = 0; for (let i = 0; i < pos.length; i += 3) far = Math.max(far, Math.hypot(pos[i], pos[i+1], pos[i+2]));
  return { type: s.type, uniforms: JSON.stringify(s.material.uniforms), aSize: st("aSize"), aAlpha: st("aAlpha"), maxRadius: far, instanceCount: g.instanceCount, camFar: window.__nahualR3f.camera.far, camPos: window.__nahualR3f.camera.position.toArray().map((v) => v.toFixed(1)), groupPos: s.parent.position.toArray().map((v) => v.toFixed(1)) };
});
console.log(gpu, JSON.stringify(stats));
const issue = await page.evaluate(() => { const p = document.querySelector("nextjs-portal"); return p?.shadowRoot?.textContent?.slice(0, 400) ?? "no portal"; });
console.log("overlay:", issue);
console.log("errors:", [...new Set(errors)].slice(0, 5));
await browser.close();
